import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/main.css";
import "./styles/buttons.css";
import "./styles/forms.css";
import "./styles/navbar.css";
import "./styles/footer.css";
import "./styles/pages.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <Navbar
            items={[
              { label: 'Home', href: '/' },
              { label: 'Contatti', href: '/contatti' },
              { label: 'Game', href: '/game' },
            ]}
          />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
