import { Poppins, Geist_Mono, Press_Start_2P } from "next/font/google";
import "./globals.css";
import "./styles/main.css";
import "./styles/buttons.css";
import "./styles/forms.css";
import "./styles/navbar.css";
import "./styles/footer.css";
import "./styles/pages.css";
import "./styles/icons.css";
import "./styles/game.css";
import "./styles/magazzino.css";
import "./styles/about.css";
import "./styles/finanze.css";
import "./styles/spesatore.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pressStart = Press_Start_2P({
  variable: "--font-press-start",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${geistMono.variable} ${pressStart.variable}`}>
        <AuthProvider>
          <Navbar
            items={[
              { label: 'Home', href: '/' },
              { label: 'Chi Siamo', href: '/chi-siamo' },
              { label: 'Contatti', href: '/contatti' },
              { label: 'Game', href: '/game' },
              { label: 'Magazzino', href: '/magazzino' },
              { label: 'Entrate/Uscite', href: '/entrate-uscite' },
              { label: 'Spesatore', href: '/spesatore' },
            ]}
          />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
